baseURL = 'https://example.org/'
locale = 'en-us'
title = 'Carson Adamson'
theme = 'hugo-developer-portfolio'

[params.plugins]
  # CSS Plugins
  [[params.plugins.css]]
  URL = "https://cdn.jsdelivr.net/npm/uikit@3.25.19/dist/css/uikit.min.css"
  # JS Plugins
  [[params.plugins.js]]
  URL = "https://cdn.jsdelivr.net/npm/uikit@3.25.19/dist/js/uikit.min.js"
  [[params.plugins.js]]
  URL = "https://cdn.jsdelivr.net/npm/uikit@3.25.19/dist/js/uikit-icons.min.js"

# navigation
[menu]
  [[menu.main]]
  name = "Lorenz"
  URL = "lorenz"

[params]
home = "Home" # What you want the homepage to show up as in the menu bar
# Meta data
description = "The personal website for Carson Adamson"
author = "Carson Adamson"

  # This contains the contact information for the footer
  [params.footer]
  email = "carsonadamson15@gmail.com"
  address = "Oklahoma City, OK"
